#!/usr/bin/env python3
"""
Generate a tailored outreach email per creator.

Reads a results CSV and writes one subject + body per row, varied by the
signals actually in the data: upload cadence, niche, size, and whether the
channel sells anything. Output is a CSV you can paste from, mail-merge, or
feed to the Gmail sequencer.

    python make_outreach.py results/creators_around_100k.csv outreach_drafts.csv

Each body carries one [WATCH] line. That is the hook, and it is left blank on
purpose - the CSV knows subscriber counts, not what happens at 4:12 in their
latest video. Everything around it is written so that filling in one sentence
turns a template into a real email.
"""

import argparse
import csv
import re
import sys

YOUR_NAME = 'JB'
YOUR_SITE = 'jbmedias.com'


def format_subs(value):
    digits = re.sub(r'[^\d]', '', str(value or ''))
    if not digits:
        return ''
    n = int(digits)
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}".rstrip('0').rstrip('.') + 'M'
    if n >= 1_000:
        return f"{round(n / 1000)}k"
    return str(n)


def cadence_line(cadence, subs):
    """The opening observation. Wrong cadence claim kills the email, so each
    case gets its own sentence rather than one line that only fits monthly."""
    if cadence == 'weekly':
        return ("You're posting weekly and holding it, which is the hard part. "
                "The question is what you'd make if the edit wasn't yours to do.")
    if cadence == 'biweekly':
        return ("You're posting every couple of weeks. In my experience that's "
                "usually the edit setting the pace rather than the ideas.")
    if cadence == 'monthly':
        return (f"I noticed you're posting about once a month. At {subs} that "
                "usually means you're cutting them yourself, and the edit is "
                "what's eating the month.")
    return ("Your upload gaps look uneven, which is almost always the edit "
            "rather than a shortage of ideas.")


def craft_line(niche):
    """What specifically I'd work on, by content type."""
    if niche == 'travel':
        return ("With travel the footage is already good. Retention comes from "
                "how the story is shaped and what the sound is doing underneath "
                "it, which is the part that's easy to lose when you're also the "
                "one who shot it.")
    if niche == 'vlog/fitness':
        return ("With training content the pacing decides everything - whether "
                "someone finishes the video or bails during the third set. Most "
                "of the drop-off I see is rhythm, not information.")
    if niche == 'agency':
        return ("For a channel that feeds a business, retention isn't vanity - "
                "it's enquiries. The people who leave at ninety seconds are the "
                "ones who never see the offer.")
    return ("Most retention problems I see aren't pacing problems, they're "
            "sound problems. The room tone drops, the music sits wrong under a "
            "beat, and people leave without knowing why.")


def sells_line(sells):
    """Only included when the channel visibly sells something."""
    if not sells:
        return None
    labels = [s.strip() for s in sells.split(',') if s.strip()]
    if not labels:
        return None
    what = {
        'store': 'a store', 'storefront': 'a storefront', 'course': 'a course',
        'membership': 'a membership', 'community': 'a community',
        'coaching': 'coaching', 'app': 'an app', 'bookings': 'bookings',
        'own site': 'your own site',
    }
    named = what.get(labels[0], labels[0])
    return (f"You've got {named} running off the back of the channel, so the "
            "videos aren't just content - they're the top of the funnel.")


TRAVEL_RE = re.compile(r'\b(travel|holiday|vacation|cruise|resort|hotel|trip|'
                       r'destination|tour|flight|passport|wander|jetset|'
                       r'explor|voyag|itinerar|nomad|abroad|getaway)\b', re.I)

FITNESS_RE = re.compile(r'\b(fit|fitness|workout|gym|train|trainer|training|'
                        r'lift|lifting|strength|muscle|physique|bodybuild|'
                        r'calisthenic|crossfit|hyrox|run|runner|running|'
                        r'marathon|triathlon|yoga|pilates|nutrition|macro|'
                        r'protein|coach|athletic|anabolic|pump)\b', re.I)


def infer_niche(row):
    """
    Work out the niche from the channel itself rather than from which result
    file it came out of. The result files overlap and are regenerated by every
    run, so provenance drifts - it put a travel channel in the fitness bucket
    and pitched it on set pacing.
    """
    blob = f"{row.get('Display Name', '')} {row.get('Sells', '')}"

    fitness = bool(FITNESS_RE.search(blob))
    travel = bool(TRAVEL_RE.search(blob))

    if travel and not fitness:
        return 'travel'
    if fitness and not travel:
        return 'vlog/fitness'

    # Nothing decisive in the name: fall back to provenance, then to a
    # niche-neutral email rather than guessing wrong.
    source = (row.get('Source') or '').strip()
    return source if source in ('travel', 'vlog/fitness', 'agency') else ''


def build_email(row):
    name = (row.get('Display Name') or '').strip()
    first = (row.get('FirstName') or '').strip() or 'there'
    subs = format_subs(row.get('YT Subscribers'))
    cadence = (row.get('Cadence') or '').strip()
    niche = infer_niche(row)

    parts = [
        f"Hey {first},",
        "",
        "[WATCH] <- one line about their most recent video, written by you",
        "",
        cadence_line(cadence, subs),
        "",
        craft_line(niche),
    ]

    extra = sells_line(row.get('Sells'))
    if extra:
        parts += ["", extra]

    parts += [
        "",
        "I put together a 90 second breakdown of one of your recent videos - "
        "three specific places where the pacing and sound are costing you "
        "retention, with the fixes. No pitch in it, just the edit notes.",
        "",
        "Want me to send it over?",
        "",
        YOUR_NAME,
        f"JB Medias - {YOUR_SITE}",
    ]

    return f"built something for {name}", "\n".join(parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source')
    parser.add_argument('destination')
    parser.add_argument('--limit', type=int, default=0)
    args = parser.parse_args()

    try:
        with open(args.source, newline='', encoding='utf-8') as handle:
            rows = list(csv.DictReader(handle))
    except FileNotFoundError:
        print(f"No such file: {args.source}", file=sys.stderr)
        return 1

    if args.limit:
        rows = rows[:args.limit]

    out_cols = ['#', 'Channel', 'FirstName', 'Email', 'Subs', 'Niche',
                'Cadence', 'Country', 'Handle', 'Subject', 'Body', 'Status']

    with open(args.destination, 'w', newline='', encoding='utf-8') as handle:
        writer = csv.DictWriter(handle, fieldnames=out_cols)
        writer.writeheader()

        for index, row in enumerate(rows, 1):
            subject, body = build_email(row)
            url = row.get('YT Channel') or ''
            match = re.search(r'/(@[\w.\-]+)', url)
            writer.writerow({
                '#': index,
                'Channel': row.get('Display Name', ''),
                'FirstName': '',
                'Email': '',
                'Subs': row.get('YT Subscribers', ''),
                'Niche': infer_niche(row),
                'Cadence': row.get('Cadence', ''),
                'Country': row.get('Country', ''),
                'Handle': match.group(1) if match else url,
                'Subject': subject,
                'Body': body,
                'Status': '',
            })

    print(f"{len(rows)} drafts -> {args.destination}", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
